FE-12
bgonzalezcbcv/cb-web pull request #25
Opened 2022-09-24 16:12 UTC by Nadia-Martinez

2022-09-26 11:33 UTC, NicolasBlumetto commented on src/pages/user/CreateUser.tsx
> +                    }}
preferiria que fuera `errors && setErrors(errors)`.

2022-09-26 11:37 UTC, NicolasBlumetto commented on src/pages/user/CreateUser.tsx
> +                <Button variant="contained" onClick={handleUserCreation} style={{marginTop: 30}}>
utilizemos `sx` en lugar de `style` en los componentes de mui, esto es para que siempre pise cualquier estilo que tenga definido

2022-09-26 11:38 UTC, NicolasBlumetto commented on src/pages/user/components/CreateUserDialog.tsx
> +        </>
Es necesario el fragment?

2022-09-26 11:41 UTC, NicolasBlumetto commented on src/pages/user/schema.json
> +		},
Agregar capaz el pattern de email

2022-09-27 21:47 UTC, marcobaldi97 commented on src/pages/user/CreateUser.tsx
> +    ]);
Ojo con esto, hay una forma mas novedosa y menos engorrosa de hacer esto desde el schema mismo. 
@NicolasBlumetto : ¿El cherrypick del improvement de los errores ya está en develop? O ¿Dejamos que sigan con el translator, no biggie?

2022-09-30 20:44 UTC, marcobaldi97 requested changes
Se ve bien, hacer cambios del schema y supongo que queda a esperar a la API

2022-09-30 20:44 UTC, marcobaldi97 commented on src/pages/user/schema.json
> +		},
Copiar el pattern de la cedula a los que tiene el estudiante.

2022-09-30 20:44 UTC, marcobaldi97 commented on src/pages/user/schema.json
> +	  	},
Cuidado que esto no controla que sea una fecha, ver https://json-schema.org/understanding-json-schema/reference/string.html#dates-and-times

2022-09-30 20:44 UTC, marcobaldi97 commented on src/pages/user/schema.json
> +	  	},
Un telefono deberia ser un string de digitos

2022-10-01 12:56 UTC, NicolasBlumetto reviewed
<img width="962" alt="Screen Shot 2022-10-01 at 09 55 57" src="https://user-images.githubusercontent.com/61328594/193410595-a7433268-ae6f-40f6-8188-eaa79b7ce5b0.png">
Aunque completes la fecha sale un error

2022-10-01 12:56 UTC, NicolasBlumetto commented on src/pages/user/CreateUser.tsx
> +    const [userCreationState, setUserCreationState] = React.useState<"idle" | "inProcess" | "success" | "fail">("idle");
se puede crear un type para el estado

2022-10-04 21:59 UTC, marcobaldi97 approved these changes

2022-10-06 23:15 UTC, Nadia-Martinez commented on src/core/ApiStore.ts
> +	console.log("Mira cpmp me corro", dataStore.loggedUser?.token);
Esto tenemos que sacarlo

2022-10-07 20:25 UTC, merged