Discount date validation
bgonzalezcbcv/cb-web pull request #26
Opened 2022-09-24 18:23 UTC by tedybear26

Also modal's accept button is disabled if there are any errors in the form or the dates.
Created separated schema for discount and payment methods and cleaned up code for that.
Changed a little how the Modal works (per instructions of Marco) and adjusted the components to the changes.

2022-09-26 10:46 UTC, NicolasBlumetto commented on src/components/modal/Modal.tsx
> +
A no ser que me este perdiendo de algo, este estado y el useEffect no son necesarios. Basicamente esta emulando el valor de la prop, se puede usar la prop directamente

2022-09-26 10:47 UTC, NicolasBlumetto commented on src/components/modal/Modal.tsx
> +
Sugiero

```
import React, { useCallback } from "react";
import { Button, Dialog, Container, Box } from "@mui/material";
import CloseIcon from "@mui/icons-material/Close";
import "./Modal.scss";

export type ModalProps = {
	show: boolean;
	title: string;
	children: React.ReactElement;
	cancelText?: string;
	acceptText?: string;
	onClose: () => void;
	onAccept: () => void;
	acceptEnabled?: boolean;
};

export default function Modal(props: ModalProps): React.ReactElement {
	const { acceptText, children, cancelText, show, title, onClose, onAccept, acceptEnabled } = props;

	const handleModalClose = useCallback(() => {
		onClose();
	}, [onClose]);

	const handleModalAccept = useCallback(() => {
		onAccept();
	}, [onAccept]);

	if (!show) return <></>;
	return (
		<Dialog open={show} onClose={handleModalClose} id="MUIModal">
			<Box className="modal">
				<CloseIcon onClick={handleModalClose} />

				<Container className="wrapper">
					<h3>{title}</h3>
					{children}
				</Container>

				<Container className="button-container">
					<Button variant="outlined" sx={{ marginRight: 2 }} onClick={handleModalClose} id="modalCancel">
						{cancelText ?? "Cancelar"}
					</Button>

					<Button variant="contained" onClick={handleModalAccept} disabled={!acceptEnabled} id="modalAccept">
						{acceptText ?? "Aceptar"}
					</Button>
				</Container>
			</Box>
		</Dialog>
	);
}

```

2022-09-26 10:59 UTC, NicolasBlumetto commented on src/components/modal/Modal.tsx
> +
Es mas tampoco estoy seguro de que memorizar el handleModalClose y el handleModalAccept aporte mucho porque solo se abre un modal a la vez. Se podria ver y si es asi se pueden sacar esos dos handlers y pasarle directamente onClose y onAccept a los botones y dialog.

2022-09-26 11:05 UTC, NicolasBlumetto requested changes
Revisar lo que puse sobre el Modal.  Tambien los scss me parece estan tabualdos pero idk. 
Por lo demas looks good

2022-09-26 11:12 UTC, NicolasBlumetto requested changes

2022-09-26 11:12 UTC, NicolasBlumetto commented on src/components/modal/Modal.tsx
> +				<Container className="button-container">
Agregarle `sx={{ display: "flex" }}>` al button container. Por defecto el container viene con display:block y hay que pisarlo para que se le apliquen los cambios de flexbox

2022-09-27 22:35 UTC, tedybear26 commented on src/components/modal/Modal.tsx
> +				<Container className="button-container">
Listo

2022-09-27 22:35 UTC, tedybear26 commented on src/components/modal/Modal.tsx
> +
Aplique la sugerencia, sobre lo otro no tengo mucha idea.

2022-09-28 21:01 UTC, Nadia-Martinez approved these changes

2022-09-30 20:32 UTC, marcobaldi97 requested changes
@tedybear26 :  Hacer los cambios del schema.

2022-09-30 20:32 UTC, marcobaldi97 commented on src/pages/student/components/AdministrativeInfo/DiscountsSection/DiscountsSection.tsx
> +import schema from "./schema.json";
Por qué usar este schema en vez del general? La gracia es que compartan validaciones y errores. En todo caso meter los cambios en el general y usar ese.

2022-09-30 20:32 UTC, marcobaldi97 commented on src/pages/student/components/AdministrativeInfo/PaymentMethodsSection/PaymentMethodSection.tsx
> +import schema from "./schema.json";
Lo mismo que en el otro caso: Usar el schema general, modificarlo de ser necesario.

2022-09-30 20:36 UTC, marcobaldi97 commented
<img width="1040" alt="Screen Shot 2022-09-30 at 17 35 12" src="https://user-images.githubusercontent.com/60588169/193352314-7eb14252-f9e2-4b7b-a643-5cb4ba5cdd53.png">
No se si le ando ladrando al perro correcto pero no me deja usar la cruz de arriba, ver imagen

2022-09-30 21:18 UTC, tedybear26 commented on src/pages/student/components/AdministrativeInfo/DiscountsSection/DiscountsSection.tsx
> +import schema from "./schema.json";
Esto es así porque el form del descuento no edita directamente al alumno, tiene un boton de agregar y eso en el dialogo. Si lo hacia con el schema general tenia que hacer unas chanchadas porque el form me devuelve la data en una estructura mucho mas grande (ej me devuelve administrative-info { discount: { la data que quiero}}

2022-09-30 21:19 UTC, tedybear26 commented on src/pages/student/components/AdministrativeInfo/PaymentMethodsSection/PaymentMethodSection.tsx
> +import schema from "./schema.json";
La misma respuesta.

2022-09-30 21:24 UTC, marcobaldi97 commented on src/pages/student/components/AdministrativeInfo/DiscountsSection/DiscountsSection.tsx
> +import schema from "./schema.json";
Personalmente me sigue pareciendo un tradeoff razonable tenes que meter data.administrative_info.discount en un par de lineas antes que tener que mantener dos schemas en vez de uno

2022-09-30 21:44 UTC, tedybear26 commented on src/pages/student/components/AdministrativeInfo/DiscountsSection/DiscountsSection.tsx
> +import schema from "./schema.json";
Ok, yo deshice eso como estaba porque lo habiamos comentado con Nico, si queres lo vuelvo para atrás

2022-10-01 14:37 UTC, marcobaldi97 approved these changes

2022-10-01 17:50 UTC, Nadia-Martinez commented
> <img alt="Screen Shot 2022-09-30 at 17 35 12" width="1040" src="https://user-images.githubusercontent.com/60588169/193352314-7eb14252-f9e2-4b7b-a643-5cb4ba5cdd53.png">
> 
> No se si le ando ladrando al perro correcto pero no me deja usar la cruz de arriba, ver imagen

A mi me anduvo, lo que si vería si podemos ponerle un `cursor: pointer` a los botones de "+" para que se vean con manito

2022-10-03 23:09 UTC, tedybear26 commented
@NicolasBlumetto REvisa si te parece bien el cambio de volver al schema general y si te parece bien dale approve.

2022-10-04 11:07 UTC, NicolasBlumetto approved these changes

2022-10-04 11:08 UTC, merged