StylingLogin
bgonzalezcbcv/cb-web pull request #27
Opened 2022-09-24 23:20 UTC by cancelasantiago

2022-09-25 16:22 UTC, NicolasBlumetto commented on src/pages/login/Login.scss
> +
Esto va a afectar a toda la app, cuidado. Te fijaste que no se cambiara en las otras paginas?

2022-09-25 16:28 UTC, NicolasBlumetto commented on src/pages/login/Login.scss
> +}
Esto tambien

2022-09-25 16:29 UTC, NicolasBlumetto commented
![Screen Shot 2022-09-25 at 13 29 03](https://user-images.githubusercontent.com/61328594/192154443-bf9ddbf0-7b2b-464f-9ed0-9dfd2a284b7e.png)
Ojo

2022-09-25 16:43 UTC, NicolasBlumetto requested changes
Voy a añadir un plugin de TS para poder modularizar bien los archivos .scss y que tengan el scope que deben

2022-09-25 16:43 UTC, NicolasBlumetto commented on src/pages/login/Login.tsx
> +						</div>
En vez de h1, usar el componente Typography con varaint="h1". Esto es para que le aplique los estilos del tema

2022-09-25 16:43 UTC, NicolasBlumetto commented on src/pages/login/Login.scss
> +
Solo para mantener un poco de orden y que sea mas facil leer lo que hace cada linea, reordenalo agrupando reglas segun lo que hacen. Ejemplo, reglas para el backroung, reglas del box mode (margenes, padding width etc etc), reglas de la fuente.
```

.loginButton {
	background: linear-gradient(to right, rgb(255, 195, 113), rgb(255, 95, 109));
	transition: all 0.3s cubic-bezier(0.47, 1.64, 0.41, 0.8) 0s !important;

	margin-top: 20% !important;
	margin-bottom: 20% !important;

	text-shadow: 1px 1px 1px black !important;
	font-weight: bold !important;
        color: white !important;
}
```

2022-09-25 16:52 UTC, NicolasBlumetto commented
En una nota mas positiva, el login esta muy lindo 🚀

2022-09-27 22:36 UTC, ignacio-carmona commented on src/pages/login/Login.tsx
> +//import { VisualComponent } from "../../core/interfaces";
```suggestion
```
Estaría bueno evitar dejar código comentado

2022-09-27 22:36 UTC, ignacio-carmona commented on src/pages/login/Login.tsx
> +	//const { width, height } = props;
```suggestion
```
Acá también estaría bueno sacar el código comentado

2022-09-29 22:26 UTC, NicolasBlumetto commented on package.json
>      "lodash": "4.17.21",
sacar caret (es el nombre del techito ^)

2022-09-29 22:29 UTC, NicolasBlumetto commented on src/pages/login/Login.tsx
> +import logo from "../../assets/Vertical.svg";
En teoria ya se puede sacar el ts-ignore

2022-09-29 22:32 UTC, marcobaldi97 commented on src/core/ApiStore.ts
>  import { Student } from "./Models";
el import de interfaces por debajo al de models

2022-09-29 22:38 UTC, NicolasBlumetto commented on src/core/ApiStore.ts
> +// 		let err = "";
El any no le va a gustar a eslint

2022-09-29 22:45 UTC, marcobaldi97 requested changes
Se ve bien, faltan lo del token, que funque la API posta y ver de cambiar el displayName por name según este excel: https://docs.google.com/spreadsheets/d/1glbp_bpLUTakcesyE__Mc-IWNQOKamheacFtiOa7M5Y/edit#gid=0

2022-09-29 22:45 UTC, marcobaldi97 commented on src/pages/login/Login.module.scss
> +	background-color: rgba(255, 255, 255, 0.15) !important;
Usar este module .scss, @NicolasBlumetto quizá pueda decirte cómo.

2022-09-29 22:45 UTC, marcobaldi97 commented on src/pages/login/Login.tsx
>  		if (errors.length > 0) return;
espacio en blanco

2022-09-29 22:45 UTC, marcobaldi97 commented on src/pages/login/Login.tsx
> +								Iniciar Sesión
Ver si podés implementar un loading mientras se contacta a la API usando https://mui.com/material-ui/react-button/#loading-button

2022-09-29 22:45 UTC, marcobaldi97 commented on src/pages/login/Login.tsx
> +				<Grid>
Este grid hace algo? En caso de que no, borrarlo.

2022-09-29 22:45 UTC, marcobaldi97 commented on src/core/DataStore.ts
> +			role: role,
displayName -> name

https://docs.google.com/spreadsheets/d/1glbp_bpLUTakcesyE__Mc-IWNQOKamheacFtiOa7M5Y/edit#gid=0

2022-10-01 20:44 UTC, cancelasantiago commented on src/core/DataStore.ts
> +			role: role,
![image](https://user-images.githubusercontent.com/62358169/193427652-2ca19ae0-76fa-41f6-9ef1-feb5de55f656.png)
ahí cambia tambien entonces?

2022-10-02 13:24 UTC, NicolasBlumetto commented on src/pages/login/Login.module.scss
> +
sacar esto, yo lo habia cambiado por que volvio?

2022-10-02 13:24 UTC, NicolasBlumetto commented on src/pages/login/Login.module.scss
> +
No podemos pisar el body, yo habia puesto un classname al Box que contenia la pagina y le habia puesto estas reglas

2022-10-04 19:22 UTC, NicolasBlumetto approved these changes

2022-10-04 19:26 UTC, marcobaldi97 approved these changes

2022-10-04 19:28 UTC, merged