FE -18
bgonzalezcbcv/cb-web pull request #28
Opened 2022-09-26 10:34 UTC by NicolasBlumetto

2022-09-27 22:49 UTC, ignacio-carmona commented on src/pages/student/components/AdministrativeInfo/AdministrativeInfo.tsx
> +						console.log(data);
eliminar console.logs()

2022-09-27 22:49 UTC, ignacio-carmona commented on src/pages/student/components/AdministrativeInfo/AdministrativeInfo.tsx
> +								dataStore.agreementTypes?.map((value, index) => {
```suggestion
								dataStore.agreementTypes.map((value, index) => {
```
Entiendo que no se necesita el '?' porque lo estás preguntando antes, no?

2022-09-27 22:49 UTC, ignacio-carmona commented on src/pages/student/components/FamilyForm/FamilyForm.tsx
> +				// i18n={{ translate: translator as Translator }}
eliminar código comentado

2022-09-27 22:49 UTC, ignacio-carmona commented on src/pages/student/schema.json
> +								"pattern": "Se deben ingresar solo los números, sin puntos ni guiones y no puede quedar vacía"
Viendo que ahora el campo admite letras, se debería cambiar este mensaje.
Quizás algo como "Se deben ingresar solamente números y letras, sin guiones ni puntos y no puede quedar vacío"

2022-09-27 22:49 UTC, ignacio-carmona commented on src/pages/student/schema.json
> +								"format": "Tiene que ser E-mail válido."
```suggestion
								"format": "Tiene que ser e-mail válido."
```

2022-09-28 19:22 UTC, marcobaldi97 commented on src/pages/student/components/AdministrativeInfo/schema.json
> +}
¿Que hace este schema acá? Se debería usar sólo el schema general y de última hacer los ajustes necesarios en el UI.

2022-09-28 19:35 UTC, marcobaldi97 requested changes

2022-09-28 19:35 UTC, marcobaldi97 commented on src/pages/student/schema.json
> +			"pattern": "^((\\d+)|([a-zA-Z]+))+$",
Este pattern funca? No me anda en regex101, te animas a chequearlo o algo?

2022-09-28 20:39 UTC, Nadia-Martinez commented on src/pages/student/components/AdministrativeInfo/schema.json
> +}
Esto quedó repetido de cuando se movió al schema de student, debería borrarse este si.

2022-09-29 21:11 UTC, tedybear26 commented on src/pages/student/schema.json
> +			"pattern": "^((\\d+)|([a-zA-Z]+))+$",
Ya lo chequee, está bien. Para chequearlo en regex101 tenes que sacarle uno de los \ al \\d: ^((\d+)|([a-zA-Z]+))+$

2022-09-29 22:58 UTC, marcobaldi97 requested changes
Se ve bien, solo hacer el cambio del import ese.

@NicolasBlumetto si no quedan mas bugs podriamos mergar esto. ¿No?

2022-09-29 22:58 UTC, marcobaldi97 commented on src/pages/student/components/StudentInfo/StudentInfo.tsx
> +import { studentAjv } from "../../StudentErrors";
Este import va en la línea 7 y el de la linea 7 va debajo del schema con un espacio en blanco de por medio.

2022-10-01 14:16 UTC, marcobaldi97 approved these changes

2022-10-01 14:17 UTC, merged