Fe 15
bgonzalezcbcv/cb-web pull request #29
Opened 2022-09-26 18:32 UTC by santiagosegundo96

2022-09-27 22:41 UTC, ignacio-carmona commented on .husky/pre-commit
> +# CI=true npm test --passWithNoTests
Recordar deshacer este cambio antes del merge

2022-09-30 20:49 UTC, marcobaldi97 commented
Cuidado que la tabulación no va de respuesta a respuesta sino que anda tocando el acordion de pregunta.

https://user-images.githubusercontent.com/60588169/193353972-829250f4-48ee-40e0-8122-b9f1b48ebd1f.mov

2022-10-02 20:20 UTC, Nadia-Martinez approved these changes
Para mí luce bien, habría que revisar lo del comentario de Nacho que supongo que tiene que ver con la build que falló pero por el lado del código creo que está pronto.

2022-10-02 23:58 UTC, santiagosegundo96 commented on .husky/pre-commit
> +# CI=true npm test --passWithNoTests
removido el comentario

2022-10-11 18:39 UTC, marcobaldi97 requested changes
Al hacer parser falla porque falla el GET a la API.

2022-10-11 18:39 UTC, marcobaldi97 commented on src/core/ApiStore.ts
> +export async function getCicleQuetions(cicleId: number): Promise<{ success: boolean; cicle_questions: QuestionCategories[] }> {
```suggestion
export async function getCicleQuestions(cicleId: number): Promise<{ success: boolean; cicle_questions: QuestionCategories[] }> {
```

2022-10-11 18:39 UTC, marcobaldi97 commented on src/core/ApiStore.ts
> +			success: response.status === 200,
También podria ser el status 304 (Not modified), agregarlo
```suggestion
			success: [200, 304].includes(response.status),
```

2022-10-11 18:39 UTC, marcobaldi97 commented on src/core/ApiStore.ts
> +			success: response.status === 200,
También podria ser el status 304 (Not modified), agregarlo
```suggestion
			success: [200, 304].includes(response.status),
```

2022-10-11 18:39 UTC, marcobaldi97 commented on src/core/ApiStore.ts
> +			success: response.status === 200,
You know the drill.

2022-10-11 18:39 UTC, marcobaldi97 commented on src/core/ApiStore.ts
> +		return response.status === 201;
You know the drill.

2022-10-11 18:39 UTC, marcobaldi97 commented on cypress/e2e/studentsBasicInfo.cy.ts
> +	const CIFieldErrorID = "#\\#\\/properties\\/ci2> :nth-child(3)";
Por qué todos estos cambios en este archivo?

2022-10-11 18:39 UTC, marcobaldi97 commented on src/core/Parsers.ts
> +	// todo: to obtain from API.
```suggestion
```

2022-10-11 18:39 UTC, marcobaldi97 commented on src/pages/student/Student.tsx
> +		<EnrollmentQuestions student={{ ...student }} onChange={debouncedSetStudent} editable={isEditable} viewMode={mode} />,
Que logras con esta copia del objeto student?

2022-10-11 18:39 UTC, marcobaldi97 commented on src/pages/student/components/EnrollmentQuestions/EnrollmentQuestions.tsx
> +	const isViewMode = viewMode == "VIEW";
```suggestion
	const isViewMode = viewMode === "VIEW";
```

2022-10-11 18:42 UTC, santiagosegundo96 commented on src/pages/student/Student.tsx
> +		<EnrollmentQuestions student={{ ...student }} onChange={debouncedSetStudent} editable={isEditable} viewMode={mode} />,
pruebas que hicimos con Nico para resolver un problema del re-render

2022-10-11 18:53 UTC, marcobaldi97 requested changes

2022-10-11 18:53 UTC, marcobaldi97 commented on src/pages/user/CreateUser.tsx
> -        if (errors.length > 0) return;
bizarro estos espacios.

2022-10-17 00:15 UTC, closed without merging