FE-13: Errors showing on student creation dialog.
bgonzalezcbcv/cb-web pull request #30
Opened 2022-09-27 21:33 UTC by marcobaldi97

![imagen](https://user-images.githubusercontent.com/60588169/192639828-ba771e82-a246-4e94-9bd6-50f5657e452a.png)

2022-09-28 20:16 UTC, ignacio-carmona commented on src/components/ErrorList/ErrorList.tsx
> +					<List>
```suggestion

					<List>
```
espacio en blanco

2022-09-28 20:16 UTC, ignacio-carmona commented on src/components/ErrorList/ErrorList.tsx
> +					</Typography>
```suggestion
					</Typography>
					
```

2022-09-28 21:08 UTC, Nadia-Martinez commented on src/pages/student/components/FamilyForm/FamilyForm.tsx
> +				// i18n={{ translate: translator as Translator }}
Podemos sacar este comentario?

2022-09-28 21:10 UTC, Nadia-Martinez reviewed
- Habría que ver si podemos mostrar los errores de los campos que usan el oneOf de alguna forma que se entienda a que se refieren.
- No estoy segura si es por algún cambio de este PR (porque no veo nada que me parezca que lo sea) pero en los modales de descuentos y métodos de pago no se están renderizando bien los inputs del json form

2022-09-28 21:25 UTC, marcobaldi97 commented
> * Habría que ver si podemos mostrar los errores de los campos que usan el oneOf de alguna forma que se entienda a que se refieren.
> 
>     * No estoy segura si es por algún cambio de este PR (porque no veo nada que me parezca que lo sea) pero en los modales de descuentos y métodos de pago no se están renderizando bien los inputs del json form

@Nadia-Martinez ahí puse los errores de los enums y lo del render de los inputs.

2022-10-01 17:48 UTC, Nadia-Martinez requested changes
Falta un tilde en "Cédula": 
<img width="615" alt="image" src="https://user-images.githubusercontent.com/47394987/193421741-4e5c0e1f-5d43-4312-a32d-abb42d3ed3ce.png">

Podemos poner esto en español? 
<img width="324" alt="image" src="https://user-images.githubusercontent.com/47394987/193421784-4c80d63e-2468-4116-8052-ce2aaf3b5564.png">

Además de eso hay que hacer un rebase, el resto luce bien para mi.

2022-10-01 21:41 UTC, Nadia-Martinez approved these changes

2022-10-01 21:42 UTC, merged