Qa 2
bgonzalezcbcv/cb-web pull request #33
Opened 2022-09-29 20:00 UTC by ignacio-carmona

2022-09-29 22:12 UTC, ignacio-carmona commented
Este PR habría que mergearlo después de QA 7

2022-10-03 20:21 UTC, marcobaldi97 requested changes

2022-10-03 20:21 UTC, marcobaldi97 commented on cypress/e2e/studentFamilyInfo.cy.ts
> +	});
Estaría bueno ver de conseguir un ancla que deje claro que ando viendo la tab que quiero probar.

2022-10-03 20:21 UTC, marcobaldi97 commented on cypress/e2e/studentFamilyInfo.cy.ts
> +	});
Estaria bueno que me hicieses el caso en donde hay errores y que me apaerece el dialog.

2022-10-03 21:17 UTC, marcobaldi97 approved these changes

2022-10-03 21:18 UTC, merged