Fe 19: Administrative Info layout change
bgonzalezcbcv/cb-web pull request #34
Opened 2022-10-01 12:44 UTC by tedybear26

Changed Administrative Information tab layout.
New Payment Methos and New Discount modals to use file uploader for the right elements.
Changed New Discount modal to be sectioned for easier adaptation in case some sections should only be shown with certain requirements.

2022-10-02 19:04 UTC, marcobaldi97 commented on package-lock.json
> +        "@material-ui/system": "^4.12.2",
Sacar el ^

2022-10-02 19:10 UTC, marcobaldi97 commented on src/components/Navbar/Navbar.tsx
>  				</div>
Te es posible cambiar los divs por boxes?

2022-10-02 19:20 UTC, marcobaldi97 requested changes
Ver los comentarios. En general se ve bien pero ojo al piojo porque tiene cierta conflictividad con el el FE-8.

2022-10-02 19:20 UTC, marcobaldi97 commented on src/components/Sidebar/Sidebar.tsx
> +import SvgLogo from "../../assets/logo_horizontal.svg";
SVG logo va por encima del scss. En general los scss van siempre al final

2022-10-02 19:20 UTC, marcobaldi97 commented on src/components/Sidebar/Sidebar.scss
> +	//background-color: rgb(247,225, 216);
Borrar comentarios

2022-10-02 19:20 UTC, marcobaldi97 commented on src/components/modal/Modal.tsx
>  import "./Modal.scss";
Espacio en blancos separando react del resto y scss del resto

2022-10-02 19:20 UTC, marcobaldi97 commented on src/components/modal/Modal.tsx
> +				</div>
Cambiar divs por boxes

2022-10-02 19:20 UTC, marcobaldi97 commented on src/pages/student/components/AdministrativeInfo/DiscountsSection/DiscountsSection.tsx
> +import FileUploader from "../../../../../components/fileUploader/FileUploader";
El file Uploader está fuera de lugar acá abajo, subirlo al resto de los componentes

2022-10-02 19:20 UTC, marcobaldi97 commented on src/pages/student/components/AdministrativeInfo/DiscountsSection/DiscountsSection.tsx
> +								<Container>
Cambiar divs por boxes y meter Typography donde haya texto, en el caso del h4, poner Typography con variante h4

2022-10-02 19:20 UTC, marcobaldi97 commented on src/pages/student/components/AdministrativeInfo/PaymentMethodsSection/PaymentMethodSection.tsx
> +import FileUploader from "../../../../../components/fileUploader/FileUploader";
Orden incorrecto, llevar con el resto de los componentes

2022-10-02 19:20 UTC, marcobaldi97 commented on src/pages/student/components/AdministrativeInfo/PaymentMethodsSection/PaymentMethodSection.tsx
> +					</Typography>
Probar con Typography variant h4

2022-10-02 19:20 UTC, marcobaldi97 commented on src/pages/student/components/AdministrativeInfo/PaymentMethodsSection/PaymentMethodSection.tsx
>  					<div>
Cambiar divs por boxes

2022-10-02 19:20 UTC, marcobaldi97 commented on src/pages/student/components/AdministrativeInfo/historyTables/DiscountHistory.tsx
>  import * as Models from "../../../../../core/Models";
Espacio separando al import de react del resto

2022-10-02 19:20 UTC, marcobaldi97 commented on src/pages/student/components/AdministrativeInfo/historyTables/PaymentMethodHistory.tsx
>  import * as Models from "../../../../../core/Models";
Espacio

2022-10-02 22:54 UTC, marcobaldi97 commented on package.json
> +    "@material-ui/system": "^4.12.2",
Sacar picos ^

2022-10-02 22:56 UTC, marcobaldi97 commented on src/components/Sidebar/Sidebar.scss
> +	//background-color: rgb(247,225, 216);
Borrar comentarios

2022-10-02 22:57 UTC, marcobaldi97 commented on src/pages/student/Student.tsx
> +	const tabLabels = ["Informacion basica", "Informacion familiar", "Informacion complementaria", "Informacion Administrativa"];
¿Esto está bién?

2022-10-02 22:57 UTC, marcobaldi97 commented on src/pages/student/schema.json
> +					"items": [
Este cambio es incorrecto. Tiene que ser items: {}

2022-10-02 22:57 UTC, marcobaldi97 commented on src/pages/student/schema.json
> +					"items": [
Lo mismo que arriba

2022-10-02 22:59 UTC, marcobaldi97 requested changes
Ver lo comentado. Especial atención a los divs en vez de Box y que los items adentro de los schemas han de ser items: {} en vez de items:[]

2022-10-03 22:40 UTC, tedybear26 commented on src/pages/student/Student.tsx
> +	const tabLabels = ["Informacion basica", "Informacion familiar", "Informacion complementaria", "Informacion Administrativa"];
A mi me lo muestra como esta en rojo y no tengo nada para subir.

2022-10-03 22:43 UTC, tedybear26 commented on package.json
> +    "@material-ui/system": "^4.12.2",
Me lo muestra sin esto

2022-10-03 22:43 UTC, tedybear26 commented on src/pages/student/schema.json
> +					"items": [
Lo ajusto cuando integren FE-8 asi queda arreglado

2022-10-03 22:47 UTC, marcobaldi97 commented on package.json
> +    "@material-ui/system": "^4.12.2",
Hacete fetch y pull

2022-10-07 21:20 UTC, Nadia-Martinez approved these changes
Se ve bien, mergeemos este.

2022-10-07 21:24 UTC, marcobaldi97 approved these changes

2022-10-08 12:00 UTC, merged