FE-14: Añadidos modos de edicion y de vista en pagina de Student.
bgonzalezcbcv/cb-web pull request #41
Opened 2022-10-06 23:10 UTC by marcobaldi97

**_También_** se añade el fetcheo del estudiante en base a la id.

Signed-off-by: marcobaldi97 <60588169+marcobaldi97@users.noreply.github.com>

2022-10-07 20:58 UTC, NicolasBlumetto commented on src/pages/student/Student.tsx
> +	console.log(student);
Se colo un console.log

2022-10-07 20:58 UTC, NicolasBlumetto commented on src/pages/student/Student.tsx
> +		);
Ponerle un cursor: pointer a esto o hacer que sea un boton

2022-10-09 18:29 UTC, Nadia-Martinez requested changes
Cuando entro a http://localhost:3000/student/2 y quiero ver la tab complementaria o familiar me explota (por lo que veo en el error hay un map siendo undefined en ambas).
Lo mismo me pasa con http://localhost:3000/student/2/edit

2022-10-09 19:11 UTC, Nadia-Martinez approved these changes

2022-10-09 19:19 UTC, merged