FE-20
bgonzalezcbcv/cb-web pull request #53
Opened 2022-10-15 00:46 UTC by cancelasantiago

quedó fe20, tengo un par de cambis para discutir del mismo los cuales si se llegan a tener que cambiar solo serían unos pocos minutos por lo cual no requeriria mucho esfuerzo

2022-10-15 18:25 UTC, marcobaldi97 requested changes
![imagen](https://user-images.githubusercontent.com/60588169/196002161-5d8dda7a-63fa-4d2d-a6cb-eedb5b1fdfd0.png)
Estaría bueno que esta página estuviese dentro de una Card (Al igual que Student) y que la tabla no termine de forma tan estravagante. Por otro lado, también podrías hacer un uso mejor del componente https://mui.com/material-ui/react-table/#data-table para filtar y ordenar. No te preocupes por el texto en ingles del componente porque hay un cambio en el tema que se hizo en el FE-21 y que cambia todo al español. Hacer rollback al package.json, no debió ser tocado siquiera.

2022-10-15 18:25 UTC, marcobaldi97 commented on package.json
> +    "stylis-plugin-rtl": "^2.1.1",
Todas estas librerias son inutiles, hay formas de hacerlo usando Material UI

2022-10-15 18:25 UTC, marcobaldi97 commented on package.json
> +    "@mui/icons-material": "^5.2.0",
Son necesarias estas librerias?

2022-10-15 18:25 UTC, marcobaldi97 commented on src/App.tsx
> +												<Route path="/studentslist" element={<StudentsList />} />
```suggestion
												<Route path="/students" element={<StudentsList />} />
```

2022-10-15 18:25 UTC, marcobaldi97 commented on src/pages/student/DefaultStudent.tsx
> +export const defaultStudents: [Student] = [
```suggestion
export const defaultStudents: [Student] = [ defaultStudent ]
```

2022-10-15 18:25 UTC, marcobaldi97 commented on src/pages/student/DefaultStudent.tsx
> +export const emptyStudents: [Student] = [
```suggestion
export const emptyStudents: [Student] = [emptyStudent]
```

2022-10-15 18:25 UTC, marcobaldi97 commented on src/pages/student/components/StudentsList/Students.tsx
> +import _ from "lodash";
Este import va arriba de react

2022-10-15 18:25 UTC, marcobaldi97 commented on src/pages/student/components/StudentsList/Students.tsx
> +import ReactLoading from "react-loading";
```suggestion
```

2022-10-15 18:25 UTC, marcobaldi97 commented on src/pages/student/components/StudentsList/Students.tsx
> +const Example = ({ type, color }: { type: any; color: string }) => <ReactLoading type={type} color={color} height={"80px"} width={"80px"} />;
```suggestion
```

2022-10-15 18:25 UTC, marcobaldi97 commented on src/pages/student/components/StudentsList/Students.tsx
> +	const [filterText, setFilterText] = React.useState("");
este state declaralo con el resto arriba

2022-10-15 18:25 UTC, marcobaldi97 commented on src/pages/student/components/StudentsList/Students.tsx
> +	const [fetchState, setFetchState] = React.useState(FetchState.loading);
React.useState ó useState, eelegite uno y sé consistente.

2022-10-15 18:25 UTC, marcobaldi97 commented on src/pages/student/components/StudentsList/StudentsList.scss
> +}
Cambiar nombre del archivo a Students.scss ó Sudents.module.scss (si lo vas a importar `import styles from "./Students.module.scss"`)

2022-10-15 18:25 UTC, marcobaldi97 commented on src/pages/student/components/StudentsList/Students.tsx
> +];
Faltan las columnas de grupo y subgrupo. (Si no aparecen en el modelo, irlas agregando igual y por el momento quedan con data vacia)

2022-10-15 18:25 UTC, marcobaldi97 commented on src/pages/student/components/StudentsList/Students.tsx
> +					}
- No usar divs, usar Box.
- En vez de usar h4, usar Typography con variant="h4"
- Dejar que si el filtro borra todo, se siga viendo la tabla.

2022-10-15 18:25 UTC, marcobaldi97 commented on src/pages/student/components/StudentsList/Students.tsx
> +									<Example type={"spin"} color={"rgb(165 165 165)"} />
```suggestion
<CircularProgress />
```

2022-10-15 18:25 UTC, marcobaldi97 commented on src/pages/student/components/StudentsList/Students.tsx
> +	);
Probablemente inncesario si usas el filtro de https://mui.com/material-ui/react-table/#data-table

2022-10-17 22:48 UTC, cancelasantiago commented on src/pages/student/components/StudentsList/Students.tsx
> +	);
Este es el buscador, no es para filtrar por grupos. Le cambie el nombre para que no genere confusiones

2022-10-17 22:54 UTC, cancelasantiago commented on src/pages/student/components/StudentsList/Students.tsx
> +					}
No entendí el ultimo punto

2022-10-18 02:28 UTC, cancelasantiago commented on src/pages/student/components/StudentsList/Students.tsx
> +];
Las pusé pero se me rompe todo, las agregué comentadas

2022-10-18 21:44 UTC, ignacio-carmona commented on src/pages/student/components/StudentsList/Students.tsx
> +/*eslint-disable*/
Es mala idea desactivar el eslint, habría que ver qué alertas se desactivan con esto y si no es mejor arreglarlas que desactivar toda la herramienta para este archivo

2022-10-18 21:44 UTC, ignacio-carmona commented on src/pages/student/components/StudentsList/data.json
> +[
Este archivo se sigue usando?

2022-10-20 20:09 UTC, Nadia-Martinez commented on src/pages/student/components/StudentsList/Students.tsx
> +			return <Button onClick={onClick}>Ir</Button>; //Link component
Esto ya está linkeado no? Podemos sacar el comentario?

2022-10-20 21:42 UTC, marcobaldi97 approved these changes

2022-10-20 21:43 UTC, merged