FE-21
bgonzalezcbcv/cb-web pull request #54
Opened 2022-10-15 21:08 UTC by marcobaldi97

[Trello Ticket](https://trello.com/c/MnPHfE88/121-3fe-21-crear-pagina-de-edici%C3%B3n-y-vista-del-perfil-del-usuario)

2022-10-19 19:09 UTC, Nadia-Martinez commented on src/core/schemas/user_info.json
> +		"name": {
Estos que son requeridos para que muestren el error es español correcto deberían tener un minLength: 1 y un errorMessage": "Este campo es requerido."

2022-10-19 19:11 UTC, Nadia-Martinez commented on src/core/schemas/user_info.json
> +					"starting_date": {
Estas fechas no las podemos hacer con el componente nuevo?

2022-10-19 19:13 UTC, Nadia-Martinez commented on src/pages/createuser/ui.json
> +				"dateFormat": "DD-MM-YYYY",
Si no me equivoco este va como "DD/MM/YYYY"

2022-10-19 19:14 UTC, marcobaldi97 commented on src/core/schemas/user_info.json
> +					"starting_date": {
Eva dijo que iba a buscarle la forma para hacerle el custom render. Santiago la andava ayudando a eso.

2022-10-19 19:17 UTC, Nadia-Martinez commented on src/pages/user/components/PersonalInfo/personal-info-ui.json
> +			"scope": "properties/phone"
Podemos ponerle el pattern y eso a este?

2022-10-19 19:18 UTC, Nadia-Martinez commented on src/pages/user/components/PersonalInfo/personal-info-ui.json
> +			"scope": "properties/email",
Este debería tener el pattern también

2022-10-19 19:18 UTC, Nadia-Martinez requested changes
- Estos inputs deberían estar en español:
![Screen Shot 2022-10-19 at 15 59 42](https://user-images.githubusercontent.com/47394987/196780440-d1229b1d-bef9-401c-9bc7-3bcd58812e27.png)
Además el Date no se ve como un campo de fecha.

- El botón de guardar no lo vi. No se porque.

- Este debería ser un campo fecha también:
![Screen Shot 2022-10-19 at 16 11 14](https://user-images.githubusercontent.com/47394987/196782596-616b5ed8-a503-4305-8f4e-8c4ed47e4865.png)

Vi que hay todos para usar el componente nuevo de fechas pero ya lo había comentado por ahí así que quedó.

2022-10-19 19:20 UTC, marcobaldi97 commented on src/pages/user/components/PersonalInfo/personal-info-ui.json
> +			"scope": "properties/email",
No está en el schema?

2022-10-19 19:20 UTC, marcobaldi97 commented on src/pages/user/components/PersonalInfo/personal-info-ui.json
> +			"scope": "properties/phone"
No está en el schema?

2022-10-20 19:46 UTC, Nadia-Martinez commented on src/pages/user/components/Absences/Absences.tsx
> +//todo: usar date input de eva.
Este todo ya lo podemos sacar no?

2022-10-20 19:47 UTC, Nadia-Martinez commented on src/pages/user/components/ComplementaryInfo/ComplementaryInformation.tsx
> +//todo: usar date input de eva.
Este todo también no?

2022-10-20 19:48 UTC, Nadia-Martinez commented on src/pages/user/components/Documents/Documents.tsx
> +//todo: usar date input de eva.
Este también

2022-10-20 19:49 UTC, Nadia-Martinez approved these changes
Fijate si se pueden sacar esos todo, pero el resto se ve bien.

2022-10-20 19:50 UTC, Nadia-Martinez commented on src/pages/user/components/PersonalInfo/personal-info-ui.json
> +			"scope": "properties/email",
Si, no dije nada entonces.

2022-10-20 19:51 UTC, Nadia-Martinez commented on src/pages/user/components/PersonalInfo/personal-info-ui.json
> +			"scope": "properties/phone"
Este también está si.

2022-10-20 19:52 UTC, Nadia-Martinez commented on src/pages/createuser/ui.json
> +				"dateFormat": "DD-MM-YYYY",
@marcobaldi97 esto está bien así entonces?

2022-10-20 23:29 UTC, merged