FE-161
bgonzalezcbcv/cb-web pull request #68
Opened 2022-10-23 18:01 UTC by santiagosegundo96

2022-10-30 21:41 UTC, tedybear26 requested changes, later dismissed
Compila con errores.
![image](https://user-images.githubusercontent.com/10677226/198902803-b3965dd0-583a-46c7-98b3-d8372ec96d4b.png)

2022-10-30 21:41 UTC, tedybear26 commented on src/pages/reportcard/ReportCardList.tsx
> +					: (period = `12/${params.row.year.getFullYear()}`);
Dejaría solo el año. Es por algo de ordenar o algo asi?

2022-10-30 21:41 UTC, tedybear26 commented on src/pages/reportcard/ReportCardList.tsx
> +			field: "ending_month",
Probaste unificar estas dos columnas? o es por un tema de como ordenarlos o algo de eso?

2022-10-30 23:03 UTC, santiagosegundo96 commented on src/pages/reportcard/ReportCardList.tsx
> +					: (period = `12/${params.row.year.getFullYear()}`);
si, se rompe el algoritmo de ordenacion

2022-10-30 23:03 UTC, santiagosegundo96 commented on src/pages/reportcard/ReportCardList.tsx
> +			field: "ending_month",
es un tema de ordenarlos

2022-10-31 19:29 UTC, marcobaldi97 approved these changes

2022-10-31 19:30 UTC, merged