FE-7: layout basico
bgonzalezcbcv/cb-web pull request #9
Opened 2022-09-08 17:50 UTC by ignacio-carmona

2022-09-08 22:38 UTC, marcobaldi97 commented
![imagen](https://user-images.githubusercontent.com/60588169/189238079-6675eb73-063b-4886-9b79-5d4d176ff312.png)
Podrás esconder la topbar en el login

2022-09-08 22:39 UTC, marcobaldi97 commented
![imagen](https://user-images.githubusercontent.com/60588169/189238182-e141bc78-9023-4158-8ee1-35530ba6a581.png)
La sombra se une entre la sidebar y la topbar

2022-09-08 22:40 UTC, marcobaldi97 commented
![imagen](https://user-images.githubusercontent.com/60588169/189238248-bacffc5d-a467-44e0-98fc-d2f23bd969d4.png)
Son hechas a mano los borders de los botones? No soy muy fan 😅

2022-09-08 22:43 UTC, marcobaldi97 commented on src/components/Navbar/Navbar.tsx
> +}
Enum here

2022-09-08 22:57 UTC, marcobaldi97 requested changes
Mirar comentarios.

2022-09-08 22:57 UTC, marcobaldi97 commented on src/components/Sidebar/Sidebar.tsx
> +				<Drawer //
Comentario...

2022-09-08 22:57 UTC, marcobaldi97 commented on src/core/userRoleHelper.ts
> +import { SidebarSection } from "../components/Sidebar/Sidebar";
No import desde components adentro del core

2022-09-08 22:57 UTC, marcobaldi97 commented on src/components/Navbar/Navbar.tsx
> +}
enum RolColor = {
    Administrador: "blue",
    Administrativo: "red",
}

Luego usarlo tipo RolColor[rol].

2022-09-09 00:53 UTC, ignacio-carmona commented on src/components/Navbar/Navbar.tsx
> +}
Fijate como lo terminé haciendo. No sé si está alineado el cambio con como me habías pedido

2022-09-12 20:12 UTC, marcobaldi97 requested changes

2022-09-12 20:12 UTC, marcobaldi97 commented on src/core/interfaces.ts
>  export interface VisualComponent {
whitespace

2022-09-12 20:14 UTC, marcobaldi97 commented
![imagen](https://user-images.githubusercontent.com/60588169/189749613-df6f14b3-8e52-47e2-b7e3-d9d1680a8c6e.png)
Es posible eliminar esos bordes de los botones?

2022-09-12 20:18 UTC, ignacio-carmona commented
> ![imagen](https://user-images.githubusercontent.com/60588169/189749613-df6f14b3-8e52-47e2-b7e3-d9d1680a8c6e.png) Es posible eliminar esos bordes de los botones?

los agregué porque están en el wirerfame así.

2022-09-14 21:59 UTC, marcobaldi97 approved these changes

2022-09-14 22:00 UTC, merged