Fe-217: Listado de alumnos inactivos
bgonzalezcbcv/cb-web pull request #97
Opened 2022-11-08 23:08 UTC by tedybear26

Tabla para listado de alumnos inactivos.
Se traen los alumnos del servidor y se muestran en una tabla. Por defecto la tabla esta ordenada por ultima fecha de actividad, mostrando los mas recientes primero.
Se puede filtrar.

2022-11-10 20:31 UTC, Nadia-Martinez commented on src/pages/students/inactive/InactiveStudents.tsx
> +	{ field: "id", headerName: "ID", disableColumnMenu: true, flex: 1, hide: true },
Deberíamos mostrar el número de referencia como identificador acá. (Los inactivos igual lo tienen igual no?)

2022-11-10 20:32 UTC, Nadia-Martinez commented on src/pages/students/inactive/InactiveStudents.tsx
> +				navigate("/student/" + thisRow.id);
Si le pasas como field a la columna "id", entonces podés aca hacer de una `const id = params.value` y ya eso lo usas en el navigate: `navigate("/student/${id}");`

2022-11-10 20:38 UTC, Nadia-Martinez requested changes
Dejé unos mini comentarios y hay que arreglar las snapshots también. En general se ve bien igual, diría que después de eso está pronto.

2022-11-10 22:48 UTC, tedybear26 commented on src/pages/students/inactive/InactiveStudents.tsx
> +	{ field: "id", headerName: "ID", disableColumnMenu: true, flex: 1, hide: true },
Agregado. Podrian no tener si se dan de baja antes de activarse, pero bueno, queda vacio y punto

2022-11-10 22:48 UTC, tedybear26 commented on src/pages/students/inactive/InactiveStudents.tsx
> +				navigate("/student/" + thisRow.id);
mejorado. Era codigo copiado del listado de alumnos

2022-11-11 03:28 UTC, cancelasantiago commented on src/pages/students/inactive/InactiveStudents.tsx
> +	{ field: "id", headerName: "ID", disableColumnMenu: true, flex: 1, hide: true },
Concuerdo, el id es un uso mas que nada por el sistema y no por el usuario, por lo cual quizas le sea indiferente. Es un cambio que podría hacerse general.

2022-11-11 18:55 UTC, Nadia-Martinez approved these changes

2022-11-11 21:07 UTC, merged